### ISSUE TITLE
Set up Github Actions to run PR checks (linters, tests)

### ISSUE THREAD

**Issue by nifadyev** [evrone/toggl-python#35]
Use this fragment as an example

```yaml
name: pr

on:
  - pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.8.3"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }} --python python${{ env.PYTHON_VERSION }}

      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: dependencies-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
          restore-keys: |
            dependencies-cache-${{ runner.os }}-

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction

      - name: Run linters & friends
        run: make lint
```
